// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqnyswyinwhwjrmqlhnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxbnlzd3lpbndod2pybXFsaG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTEyNjQsImV4cCI6MjA2MDU2NzI2NH0.PSCbeA1ITrv5eAwKXa1yOog9qF1jBvigPqLsXhodEoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);